package com.ruoyi.harness.core;

import static org.junit.jupiter.api.Assertions.*;
import com.ruoyi.harness.api.*;
import com.ruoyi.harness.capability.*;
import com.ruoyi.harness.core.domain.*;
import com.ruoyi.harness.core.port.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;import java.util.concurrent.atomic.AtomicLong;
import org.junit.jupiter.api.*;import tools.jackson.databind.*;

class HarnessLifecycleTest {
 private final ObjectMapper mapper=new ObjectMapper();private final AppRepo apps=new AppRepo();private final VersionRepo versions=new VersionRepo();private final LogRepo logs=new LogRepo();
 private final AppRegistryService appService=new AppRegistryService(apps);private VersionService versionService;private PublicationService publication;private HarnessRuntimeService runtime;
 @BeforeEach void setUp(){CapabilityRegistry registry=new CapabilityRegistry();versionService=new VersionService(appService,versions,new FakeEngine(mapper),new ValidationCapabilityInvoker(registry,new JsonSchemaValidator(),mapper),mapper);publication=new PublicationService(appService,versionService,apps,versions,new PublishedArtifactCache());runtime=new HarnessRuntimeService(appService,versionService,versions,new FakeEngine(mapper),(n,i,c)->mapper.createObjectNode(),(p,i)->i.permissions().contains(p),logs,new PublishedArtifactCache(),mapper);}
 @Test void createPublishHotUpdatePinAndRollback(){AppDescriptor app=appService.create(new AppRegistryService.AppMutation("customer-dashboard","Customers","","Customers","user",1,"access"),7L);
   HarnessAppVersion v1=version(app.id(),1,"v1",VersionStatus.VALIDATED);publication.publish(app.appKey(),v1.getId(),7L);RuntimeIdentity user=new RuntimeIdentity(8L,"u",Set.of("access"));
   assertEquals("v1",runtime.render(app.appKey(),new RenderRequest(null,null),user,"r","en").page().path("title").asText());
   HarnessAppVersion v2=version(app.id(),2,"v2",VersionStatus.VALIDATED);publication.publish(app.appKey(),v2.getId(),7L);
   assertEquals("v2",runtime.render(app.appKey(),new RenderRequest(null,null),user,"r","en").page().path("title").asText());
   RuntimeResponse pinned=runtime.action(app.appKey(),"go",new ActionRequest(v1.getId(),mapper.createObjectNode(),mapper.createObjectNode()),user,"r","en");assertEquals("v1",pinned.effects().path("version").asText());
   publication.rollback(app.appKey(),v1.getId(),7L);assertEquals("v1",runtime.render(app.appKey(),new RenderRequest(null,null),user,"r","en").page().path("title").asText());assertFalse(logs.rows.isEmpty());}
 @Test void publishedSourceIsImmutable(){AppDescriptor app=appService.create(new AppRegistryService.AppMutation("immutable-app","Immutable","","Immutable","x",1,"access"),1L);HarnessAppVersion v=version(app.id(),1,"x",VersionStatus.PUBLISHED);HarnessException e=assertThrows(HarnessException.class,()->versionService.updateSource(app.appKey(),v.getId(),"changed"));assertEquals(HarnessErrorCode.VERSION_IMMUTABLE,e.getCode());}
 @Test void disabledAndUnauthorizedAppsRejectRenderAndAction(){AppDescriptor app=appService.create(new AppRegistryService.AppMutation("secure-app","Secure","","Secure","x",1,"access"),1L);HarnessAppVersion v=version(app.id(),1,"x",VersionStatus.PUBLISHED);apps.setPublishedVersion(app.id(),v.getId(),1L);RuntimeIdentity denied=new RuntimeIdentity(9L,"x",Set.of());assertEquals(HarnessErrorCode.APP_ACCESS_DENIED,assertThrows(HarnessException.class,()->runtime.render(app.appKey(),new RenderRequest(null,null),denied,"r","en")).getCode());appService.setEnabled(app.appKey(),false,1L);RuntimeIdentity allowed=new RuntimeIdentity(9L,"x",Set.of("access"));assertEquals(HarnessErrorCode.APP_DISABLED,assertThrows(HarnessException.class,()->runtime.action(app.appKey(),"go",new ActionRequest(v.getId(),null,null),allowed,"r","en")).getCode());}
 @Test void versionCannotBeUsedAcrossApplications(){AppDescriptor a=appService.create(new AppRegistryService.AppMutation("first-app","First","","First","x",1,"a"),1L);AppDescriptor b=appService.create(new AppRegistryService.AppMutation("second-app","Second","","Second","x",1,"b"),1L);HarnessAppVersion av=version(a.id(),1,"a",VersionStatus.PUBLISHED);HarnessException e=assertThrows(HarnessException.class,()->versionService.require(b.appKey(),av.getId()));assertEquals(HarnessErrorCode.VERSION_OWNERSHIP_INVALID,e.getCode());}
 private HarnessAppVersion version(Long appId,long number,String source,VersionStatus status){HarnessAppVersion v=new HarnessAppVersion();v.setAppId(appId);v.setVersionNo(number);v.setSdkVersion("1");v.setSource(source);v.setSourceHash(hash(source));v.setStatus(status);v.setCreatedAt(Instant.now());versions.insert(v);return v;}
 private static String hash(String source){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(source.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new RuntimeException(e);}}
 static class FakeEngine implements HarnessScriptEngine {private final ObjectMapper m;FakeEngine(ObjectMapper m){this.m=m;}public ValidationResult validate(ScriptArtifact a){return new ValidationResult(true,List.of(),hash(a.source()));}public ScriptExecutionResult execute(ScriptArtifact a,ScriptExecutionContext c){JsonNode v="PAGE".equals(c.entryType())?m.valueToTree(Map.of("type","page","title",a.source(),"children",List.of())):m.valueToTree(Map.of("version",a.source()));return new ScriptExecutionResult(true,v,List.of(),null,0,0,1);}}
 static class AppRepo implements HarnessAppRepository {Map<Long,HarnessApp> rows=new LinkedHashMap<>();AtomicLong ids=new AtomicLong();public HarnessApp findByKey(String k){return rows.values().stream().filter(a->a.getAppKey().equals(k)).findFirst().orElse(null);}public HarnessApp findById(Long id){return rows.get(id);}public List<HarnessApp> findAll(){return new ArrayList<>(rows.values());}public int insert(HarnessApp a){a.setId(ids.incrementAndGet());rows.put(a.getId(),a);return 1;}public int update(HarnessApp a){rows.put(a.getId(),a);return 1;}public int setEnabled(Long id,boolean enabled,Long actor){rows.get(id).setEnabled(enabled);return 1;}public int setPublishedVersion(Long id,Long versionId,Long actor){rows.get(id).setPublishedVersionId(versionId);return 1;}}
 static class VersionRepo implements HarnessVersionRepository {Map<Long,HarnessAppVersion> rows=new LinkedHashMap<>();AtomicLong ids=new AtomicLong();public HarnessAppVersion findById(Long id){return rows.get(id);}public List<HarnessAppVersion> findByAppId(Long id){return rows.values().stream().filter(v->v.getAppId().equals(id)).toList();}public Long nextVersionNo(Long id){return findByAppId(id).stream().mapToLong(HarnessAppVersion::getVersionNo).max().orElse(0)+1;}public int insert(HarnessAppVersion v){v.setId(ids.incrementAndGet());rows.put(v.getId(),v);return 1;}public int updateDraftSource(Long id,String source,VersionStatus s){var v=rows.get(id);v.setSource(source);v.setStatus(s);v.setSourceHash(null);return 1;}public int updateValidation(Long id,String h,VersionStatus s,Instant at){var v=rows.get(id);v.setSourceHash(h);v.setStatus(s);v.setValidatedAt(at);return 1;}public int updateStatus(Long id,VersionStatus s,Instant at){var v=rows.get(id);v.setStatus(s);v.setPublishedAt(at);return 1;}public int deleteDraft(Long id){rows.remove(id);return 1;}}
 static class LogRepo implements ExecutionLogRepository {List<ExecutionLog> rows=new ArrayList<>();public int insert(ExecutionLog l){rows.add(l);return 1;}public List<ExecutionLog> search(Map<String,Object> f){return rows;}}
}
