package com.ruoyi.harness.ai.model;

public enum AiErrorCode {
    AI_DISABLED, AI_PROVIDER_UNAVAILABLE, AI_PROVIDER_AUTH_FAILED, AI_RATE_LIMITED,
    AI_TIMEOUT, AI_RESPONSE_INVALID, AI_SCRIPT_INVALID, AI_CAPABILITY_UNKNOWN,
    AI_CONTEXT_TOO_LARGE, AI_SESSION_NOT_FOUND, AI_SESSION_ACCESS_DENIED,
    AI_SESSION_ARCHIVED, AI_DRAFT_NOT_FOUND
}
