package com.ruoyi.harness.api;

public enum HarnessErrorCode {
    SCRIPT_PARSE_ERROR, SCRIPT_VALIDATION_ERROR, SCRIPT_TIMEOUT, SCRIPT_RUNTIME_ERROR,
    CAPABILITY_NOT_FOUND, CAPABILITY_INPUT_INVALID, CAPABILITY_OUTPUT_INVALID,
    CAPABILITY_PERMISSION_DENIED, CAPABILITY_POLICY_DENIED, CAPABILITY_EXECUTION_ERROR,
    CAPABILITY_CALL_LIMIT_EXCEEDED, UI_SCHEMA_INVALID, INPUT_LIMIT_EXCEEDED,
    OUTPUT_LIMIT_EXCEEDED, LOG_LIMIT_EXCEEDED, APP_NOT_FOUND, APP_DISABLED,
    APP_ACCESS_DENIED, APP_VERSION_NOT_FOUND, VERSION_IMMUTABLE, VERSION_STATE_INVALID,
    VERSION_OWNERSHIP_INVALID, APP_KEY_CONFLICT, CAPABILITY_CONFLICT, ACTION_NOT_FOUND
}
