package com.ruoyi.harness.ai;

import static org.junit.jupiter.api.Assertions.*;
import com.ruoyi.harness.ai.context.AiContextAssembler;
import com.ruoyi.harness.ai.model.*;
import com.ruoyi.harness.ai.port.*;
import com.ruoyi.harness.ai.service.*;
import com.ruoyi.harness.api.*;
import com.ruoyi.harness.capability.*;
import com.ruoyi.harness.core.*;
import com.ruoyi.harness.core.domain.*;
import com.ruoyi.harness.core.port.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.*;

class AiBuilderServiceTest {
    @Test void repairsInMemoryThenEditsPublishedAppAsANewDraft(){ObjectMapper mapper=new ObjectMapper();AppRepo appRepo=new AppRepo();VersionRepo versionRepo=new VersionRepo();SessionRepo sessionRepo=new SessionRepo();MessageRepo messageRepo=new MessageRepo();CapabilityRegistry registry=new CapabilityRegistry();FakeEngine engine=new FakeEngine(mapper);
        AppRegistryService apps=new AppRegistryService(appRepo);ValidationCapabilityInvoker validation=new ValidationCapabilityInvoker(registry,new JsonSchemaValidator(),mapper);VersionService versions=new VersionService(apps,versionRepo,engine,validation,mapper);PublicationService publication=new PublicationService(apps,versions,appRepo,versionRepo,new PublishedArtifactCache());
        QueueModel model=new QueueModel(List.of(result("bad"),result("good-v1"),result("good-v2")));AiGenerationValidator generated=new AiGenerationValidator(engine,registry,validation,mapper,1024);AiPreviewService previews=new AiPreviewService(engine,registry,new JsonSchemaValidator(),(p,c)->true,CapabilityAuditSink.noop(),mapper);
        Set<String> denied=new HashSet<>();AiBuilderService builder=new AiBuilderService(true,"test","model",2,.2,1000,1500000,model,new AiContextAssembler(registry,mapper,20),generated,sessionRepo,messageRepo,apps,versions,publication,previews,p->{if(denied.contains(p))throw new SecurityException("denied");},mapper);
        var session=builder.createSession(null,"Customer Center",7L);var first=builder.generate(session.session().sessionKey(),"build it",7L);
        assertEquals(2,model.calls);assertEquals("good-v1",first.source());assertTrue(first.validation().valid());assertEquals(1,versionRepo.rows.size());HarnessAiException access=assertThrows(HarnessAiException.class,()->builder.get(session.session().sessionKey(),8L));assertEquals(AiErrorCode.AI_SESSION_ACCESS_DENIED,access.getCode());
        denied.add("harness:app:publish");assertThrows(SecurityException.class,()->builder.publish(session.session().sessionKey(),7L));denied.clear();builder.publish(session.session().sessionKey(),7L);HarnessAppVersion published=versionRepo.findById(first.versionId());assertEquals(VersionStatus.PUBLISHED,published.getStatus());
        var second=builder.generate(session.session().sessionKey(),"change title",7L);assertEquals(2,versionRepo.rows.size());assertNotEquals(first.versionId(),second.versionId());assertEquals("good-v1",published.getSource());assertEquals(VersionStatus.PUBLISHED,published.getStatus());assertEquals(VersionStatus.VALIDATED,versionRepo.findById(second.versionId()).getStatus());builder.publish(session.session().sessionKey(),7L);assertEquals(VersionStatus.SUPERSEDED,published.getStatus());}

    private static AiGenerationResult result(String source){return new AiGenerationResult("done",source,List.of(),"m","p",Usage.empty());}
    static class QueueModel implements HarnessAiModel {final ArrayDeque<AiGenerationResult> results;int calls;QueueModel(List<AiGenerationResult> values){results=new ArrayDeque<>(values);}public AiGenerationResult generate(AiGenerationRequest request){calls++;return results.remove();}}
    static class FakeEngine implements HarnessScriptEngine {final ObjectMapper mapper;FakeEngine(ObjectMapper mapper){this.mapper=mapper;}public ValidationResult validate(ScriptArtifact a){boolean valid=!"bad".equals(a.source());return new ValidationResult(valid,valid?List.of():List.of(new Diagnostic("error","SCRIPT_PARSE_ERROR","bad",1,1)),"sha256:"+a.source());}public ScriptExecutionResult execute(ScriptArtifact a,ScriptExecutionContext c){return new ScriptExecutionResult(true,mapper.valueToTree(Map.of("type","page","title",a.source(),"children",List.of())),List.of(),null,0,0,1);}}
    static class AppRepo implements HarnessAppRepository {final Map<Long,HarnessApp> rows=new LinkedHashMap<>();final AtomicLong ids=new AtomicLong();public HarnessApp findByKey(String key){return rows.values().stream().filter(a->a.getAppKey().equals(key)).findFirst().orElse(null);}public HarnessApp findByKeyForUpdate(String key){return findByKey(key);}public HarnessApp findById(Long id){return rows.get(id);}public List<HarnessApp> findAll(){return new ArrayList<>(rows.values());}public int insert(HarnessApp a){a.setId(ids.incrementAndGet());rows.put(a.getId(),a);return 1;}public int update(HarnessApp a){rows.put(a.getId(),a);return 1;}public int setEnabled(Long id,boolean enabled,Long actor){rows.get(id).setEnabled(enabled);return 1;}public int setPublishedVersion(Long id,Long versionId,Long actor){rows.get(id).setPublishedVersionId(versionId);return 1;}}
    static class VersionRepo implements HarnessVersionRepository {final Map<Long,HarnessAppVersion> rows=new LinkedHashMap<>();final AtomicLong ids=new AtomicLong();public HarnessAppVersion findById(Long id){return rows.get(id);}public List<HarnessAppVersion> findByAppId(Long appId){return rows.values().stream().filter(v->v.getAppId().equals(appId)).sorted(Comparator.comparing(HarnessAppVersion::getVersionNo).reversed()).toList();}public Long nextVersionNo(Long appId){return findByAppId(appId).stream().mapToLong(HarnessAppVersion::getVersionNo).max().orElse(0)+1;}public int insert(HarnessAppVersion v){v.setId(ids.incrementAndGet());rows.put(v.getId(),v);return 1;}public int updateDraftSource(Long id,String source,VersionStatus status){var v=rows.get(id);v.setSource(source);v.setSourceHash(null);v.setValidatedAt(null);v.setStatus(status);return 1;}public int updateValidation(Long id,String hash,VersionStatus status,Instant at){var v=rows.get(id);v.setSourceHash(hash);v.setStatus(status);v.setValidatedAt(at);return 1;}public int updateStatus(Long id,VersionStatus status,Instant at){var v=rows.get(id);v.setStatus(status);v.setPublishedAt(at);return 1;}public int deleteDraft(Long id){rows.remove(id);return 1;}}
    static class SessionRepo implements AiSessionRepository {final Map<Long,AiSession> rows=new LinkedHashMap<>();final AtomicLong ids=new AtomicLong();public AiSession findByKey(String key){return rows.values().stream().filter(s->s.getSessionKey().equals(key)).findFirst().orElse(null);}public List<AiSession> findByCreatedBy(Long user){return rows.values().stream().filter(s->s.getCreatedBy().equals(user)).toList();}public int insert(AiSession s){s.setId(ids.incrementAndGet());rows.put(s.getId(),s);return 1;}public int updateLink(Long id,Long appId,Long versionId,Instant at){var s=rows.get(id);s.setAppId(appId);s.setActiveVersionId(versionId);s.setUpdatedAt(at);return 1;}public int archive(Long id,Instant at){rows.get(id).setStatus("ARCHIVED");return 1;}}
    static class MessageRepo implements AiMessageRepository {final List<AiStoredMessage> rows=new ArrayList<>();final AtomicLong ids=new AtomicLong();public List<AiStoredMessage> findBySessionId(Long id){return rows.stream().filter(m->m.getSessionId().equals(id)).toList();}public int insert(AiStoredMessage m){m.setId(ids.incrementAndGet());rows.add(m);return 1;}}
}
