package com.ruoyi.harness.capability;
import static org.junit.jupiter.api.Assertions.*;import com.ruoyi.harness.api.*;import java.util.*;import java.util.concurrent.atomic.AtomicBoolean;import org.junit.jupiter.api.*;import tools.jackson.databind.*;
class CapabilityBridgeTest {private final ObjectMapper mapper=new ObjectMapper();private final CapabilityRegistry registry=new CapabilityRegistry();
 @Test void registrationCollisionFails(){CapabilityDefinition d=definition(ctx->mapper.createObjectNode());registry.register(d);assertThrows(HarnessException.class,()->registry.register(d));}
 @Test void permissionDenialPreventsHandlerAndIsAudited(){AtomicBoolean called=new AtomicBoolean();List<CapabilityAuditEvent> audit=new ArrayList<>();registry.register(definition(ctx->{called.set(true);return mapper.createObjectNode();}));CapabilityBridge bridge=new CapabilityBridge(registry,new JsonSchemaValidator(),(p,c)->false,CapabilityPolicy.allowAll(),audit::add);HarnessException e=assertThrows(HarnessException.class,()->bridge.invoke("protected",mapper.createObjectNode(),context(9L)));assertEquals(HarnessErrorCode.CAPABILITY_PERMISSION_DENIED,e.getCode());assertFalse(called.get());assertEquals("DENIED",audit.get(0).status());}
 @Test void scriptInputCannotForgeTrustedIdentity(){registry.register(definition(ctx->mapper.valueToTree(Map.of("seen",ctx.userId()))));CapabilityBridge bridge=new CapabilityBridge(registry,new JsonSchemaValidator(),(p,c)->true,CapabilityPolicy.allowAll(),CapabilityAuditSink.noop());JsonNode input=mapper.valueToTree(Map.of("userId",1));assertEquals(9,bridge.invoke("protected",input,context(9L)).path("seen").asInt());}
 @Test void invalidInputStopsHandler(){AtomicBoolean called=new AtomicBoolean();JsonNode schema;try{schema=mapper.readTree("{\"type\":\"object\",\"required\":[\"name\"]}");}catch(Exception e){throw new RuntimeException(e);}registry.register(new CapabilityDefinition("typed","1","",schema,null,"",RiskLevel.READ,(i,c)->{called.set(true);return i;}));CapabilityBridge bridge=new CapabilityBridge(registry,new JsonSchemaValidator(),(p,c)->true,CapabilityPolicy.allowAll(),CapabilityAuditSink.noop());assertThrows(HarnessException.class,()->bridge.invoke("typed",mapper.createObjectNode(),context(9L)));assertFalse(called.get());}
 private CapabilityDefinition definition(java.util.function.Function<CapabilityContext,JsonNode> handler){return new CapabilityDefinition("protected","1","",null,null,"p",RiskLevel.READ,(i,c)->handler.apply(c));}
 private CapabilityContext context(long id){return new CapabilityContext(id,"user",Set.of(),"app",1L,"r","t");}}
