<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {harnessApi} from '../runtime-client/api';
import type {ActionBinding,AiSessionSummary,AiSessionView,AiStatus,AiStoredMessage,AppDescriptor,CapabilityView,Diagnostic,PageNode,VersionDescriptor} from '../types';
import ConversationPanel from './ConversationPanel.vue';import PreviewPanel from './PreviewPanel.vue';import BuilderToolbar from './BuilderToolbar.vue';import CapabilityUsagePanel from './CapabilityUsagePanel.vue';import DiagnosticsPanel from './DiagnosticsPanel.vue';

const props=withDefaults(defineProps<{canPublish?:boolean}>(),{canPublish:true});
const status=ref<AiStatus>();const apps=ref<AppDescriptor[]>([]);const catalog=ref<CapabilityView[]>([]);const sessions=ref<AiSessionSummary[]>([]);const session=ref<AiSessionView>();const title=ref('');const selectedApp=ref('');
const source=ref('');const savedSource=ref('');const diagnostics=ref<Diagnostic[]>([]);const validationKnown=ref(false);const valid=ref(false);const used=ref<string[]>([]);const page=ref<PageNode>();const error=ref('');const historyError=ref('');const previewError=ref('');const toast=ref('');
const creating=ref(false),loadingSessions=ref(false),resumingKey=ref(''),generating=ref(false),previewing=ref(false),publishing=ref(false),validating=ref(false),published=ref(false);let localId=-1;
const messages=computed(()=>session.value?.messages||[]);const version=computed(()=>session.value?.activeVersion);const dirty=computed(()=>source.value!==savedSource.value);const ready=computed(()=>!!session.value);
const fail=(e:any,fallback:string)=>`${e?.code?e.code+': ':''}${e?.message||fallback}`;
const formatDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString()};
const inspectCapabilities=(script:string)=>Array.from(script.matchAll(/harness\.call\(\s*(['"])([^'"]+)\1/g),match=>match[2]).filter((value,index,all)=>all.indexOf(value)===index);
const loadSessions=async()=>{loadingSessions.value=true;historyError.value='';try{sessions.value=await harnessApi.aiSessions()}catch(e){sessions.value=[];historyError.value=fail(e,'Session history is unavailable')}finally{loadingSessions.value=false}};
const hydrate=()=>{source.value=session.value?.activeVersion?.source||'';savedSource.value=source.value;published.value=session.value?.activeVersion?.status==='PUBLISHED';valid.value=session.value?.activeVersion?.status==='VALIDATED'||published.value;validationKnown.value=!!session.value?.activeVersion&&session.value.activeVersion.status!=='DRAFT';diagnostics.value=session.value?.activeVersion?.diagnostics||[];used.value=inspectCapabilities(source.value);page.value=undefined;previewError.value='';toast.value=''};
const create=async()=>{creating.value=true;error.value='';try{session.value=await harnessApi.createAiSession({appKey:selectedApp.value||null,title:title.value.trim()||'Untitled Harness app'});hydrate();void loadSessions()}catch(e){error.value=fail(e,'Unable to create Builder session')}finally{creating.value=false}};
const resume=async(key:string)=>{resumingKey.value=key;error.value='';try{session.value=await harnessApi.getAiSession(key);hydrate()}catch(e){error.value=fail(e,'Unable to restore Builder session')}finally{resumingKey.value=''}};
const returnToSessions=()=>{session.value=undefined;source.value='';savedSource.value='';diagnostics.value=[];used.value=[];page.value=undefined;error.value='';previewError.value='';toast.value='';void loadSessions()};
const push=(role:AiStoredMessage['role'],content:string)=>{if(!session.value)return;session.value.messages.push({id:localId--,role,content,createdAt:new Date().toISOString()})};
const send=async(message:string)=>{if(!session.value)return;generating.value=true;error.value='';page.value=undefined;push('USER',message);try{const result=await harnessApi.sendAiMessage(session.value.session.sessionKey,message);push('ASSISTANT',result.assistantMessage);source.value=result.source;savedSource.value=result.source;diagnostics.value=result.validation.diagnostics;valid.value=result.validation.valid;validationKnown.value=true;used.value=result.capabilitiesUsed;published.value=false;session.value.session.appKey=result.appKey;session.value.session.activeVersionId=result.versionId;session.value.activeVersion={id:result.versionId,appId:session.value.app?.id||0,versionNo:result.versionNo,sdkVersion:'1',source:result.source,status:result.validation.valid?'VALIDATED':'REJECTED'};if(result.validation.valid)await preview();void loadSessions()}catch(e){error.value=fail(e,'Generation failed')}finally{generating.value=false}};
const save=async()=>{if(!session.value?.session.appKey||!version.value||published.value)return;error.value='';try{const updated=await harnessApi.saveSource(session.value.session.appKey,version.value.id,source.value) as VersionDescriptor;session.value.activeVersion=updated;savedSource.value=source.value;used.value=inspectCapabilities(source.value);valid.value=false;validationKnown.value=false;page.value=undefined}catch(e){error.value=fail(e,'Unable to save draft')}};
const validate=async()=>{if(!session.value)return;validating.value=true;error.value='';try{if(dirty.value)await save();const result=await harnessApi.validateAi(session.value.session.sessionKey);diagnostics.value=result.diagnostics;valid.value=result.valid;validationKnown.value=true;if(session.value.activeVersion)session.value.activeVersion.status=result.valid?'VALIDATED':'REJECTED'}catch(e){error.value=fail(e,'Validation failed')}finally{validating.value=false}};
const preview=async()=>{if(!session.value)return;previewing.value=true;previewError.value='';try{const result=await harnessApi.previewAi(session.value.session.sessionKey,{versionId:session.value.session.activeVersionId});page.value=result.page}catch(e){previewError.value=fail(e,'Preview failed')}finally{previewing.value=false}};
const previewAction=async(action:ActionBinding,input:Record<string,any>)=>{if(!session.value)return;previewError.value='';try{const result=await harnessApi.previewAi(session.value.session.sessionKey,{versionId:session.value.session.activeVersionId,actionName:action.name,input,state:{}});if(result.page)page.value=result.page;if(result.effects?.toast)toast.value=String(result.effects.toast.message||'');if(result.effects?.refresh)await preview()}catch(e){previewError.value=fail(e,'Preview action failed')}};
const publish=async()=>{if(!session.value)return;publishing.value=true;error.value='';try{await harnessApi.publishAi(session.value.session.sessionKey);published.value=true;if(session.value.activeVersion)session.value.activeVersion.status='PUBLISHED';toast.value='Published successfully';void loadSessions()}catch(e){error.value=fail(e,'Publish failed')}finally{publishing.value=false}};
onMounted(async()=>{void loadSessions();try{[status.value,catalog.value]=await Promise.all([harnessApi.aiStatus(),harnessApi.capabilities()]);apps.value=await harnessApi.listApps().catch(()=>[])}catch(e){error.value=fail(e,'Unable to load AI Builder')}});
</script>
<template><div class="ai-builder"><div v-if="error" role="alert" class="harness-error ai-global-error">{{error}}</div><div v-if="toast" role="status" class="ai-toast">{{toast}}</div>
  <section v-if="!ready" class="ai-start"><h2>Harness AI Builder</h2><p>Describe an application in natural language. AI creates an ordinary Harness draft; validation, preview permissions and publication remain controlled by RuoYi.</p><div v-if="status&&!status.enabled" class="harness-error">AI_DISABLED: Configure <code>HARNESS_AI_*</code> server settings to generate apps.</div><label>Session title<input v-model="title" placeholder="Customer dashboard"/></label><label>Edit an existing app (optional)<select v-model="selectedApp"><option value="">Create a new app</option><option v-for="app in apps" :key="app.appKey" :value="app.appKey">{{app.name}} ({{app.appKey}})</option></select></label><button class="primary" :disabled="creating" @click="create">{{creating?'Creating…':'Open Builder'}}</button>
    <div class="ai-session-history"><header><h3>Recent sessions</h3><button :disabled="loadingSessions" @click="loadSessions">{{loadingSessions?'Loading…':'Refresh'}}</button></header><p v-if="historyError" class="muted">{{historyError}}</p><p v-else-if="!loadingSessions&&!sessions.length" class="muted">No saved Builder sessions yet.</p><ul v-else><li v-for="item in sessions" :key="item.sessionKey"><div><strong>{{item.title}}</strong><small>{{item.appKey||'New application'}} · {{formatDate(item.updatedAt)}}</small></div><span class="session-status" :class="item.status.toLowerCase()">{{item.status}}</span><button :disabled="item.status!=='ACTIVE'||resumingKey===item.sessionKey" @click="resume(item.sessionKey)">{{resumingKey===item.sessionKey?'Opening…':item.status==='ACTIVE'?'Continue':'Archived'}}</button></li></ul></div>
  </section>
  <template v-else><div class="ai-session-nav"><button @click="returnToSessions">← Sessions</button><strong>{{session?.session.title}}</strong></div><BuilderToolbar :has-draft="!!source" :valid="valid&&!dirty" :generating="generating||validating" :previewing="previewing" :publishing="publishing" :can-publish="props.canPublish" :published="published" @validate="validate" @preview="preview" @publish="publish"/><div class="ai-workspace"><ConversationPanel :messages="messages" :generating="generating" @send="send"/><PreviewPanel :page="page" :loading="previewing" :error="previewError" @action="previewAction"/></div><section class="ai-source"><header><h3>Draft source</h3><span>Version {{version?.versionNo||'—'}} · {{version?.status||'No draft'}}</span></header><textarea v-model="source" spellcheck="false" :disabled="published"/><div><button :disabled="!dirty||published" @click="save">Save Draft</button><small v-if="published"> Published source is immutable; ask AI for another change to create a new draft.</small></div></section><div class="ai-detail-grid"><DiagnosticsPanel :diagnostics="diagnostics" :valid="validationKnown?valid:undefined"/><CapabilityUsagePanel :used="used" :catalog="catalog"/></div></template>
</div></template>
